services:
  orders:
    image: weshigbee/examples-super-orders:2.2
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/arm64"
        - "linux/amd64"
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - "*.pyc"
            - "__pycache__/"
            - ".git/"
            - "uv.lock"
            - "*.sh"
    labels:
      - "app.version=2.2"
      - "app.description=SuperOrder Processing Platform"
      - "app.maintainer=wesdemos"
